from pydantic import BaseModel, Field


class SolutionFeature(BaseModel):
    icon: str = Field(description="Emoji icon for the feature")
    text: str = Field(description="Short feature description")


class Benefit(BaseModel):
    icon: str = Field(description="Emoji icon")
    title: str = Field(description="Benefit title (3-5 words)")
    description: str = Field(description="Benefit description (1-2 sentences)")


class Testimonial(BaseModel):
    name: str = Field(description="Full name")
    role: str = Field(description="Job title / company")
    quote: str = Field(description="Testimonial quote with specific result")


class Step(BaseModel):
    number: int
    title: str = Field(description="Step title (2-4 words)")
    description: str = Field(description="Step description (1 sentence)")


class FAQ(BaseModel):
    question: str
    answer: str


class LandingPageContent(BaseModel):
    """All placeholder values for the landing page template.

    Generated by Claude from a PRDContent. Each field maps to a
    {{placeholder}} in the landing_v1.html template.
    """

    # Hero section
    headline: str = Field(description="Main headline, < 10 words, benefit-oriented")
    subheadline: str = Field(description="Supporting text, < 25 words")
    cta_text: str = Field(description="CTA button text, 2-5 words")
    cta_subtext: str = Field(default="", description="Text below CTA, < 10 words")

    # Problem section
    problem_title: str = Field(default="The problem you know too well")
    problem_description: str = Field(description="Pain point description, 2-3 sentences")
    problem_bullets: list[str] = Field(
        min_length=3, max_length=3, description="3 specific pain points"
    )

    # Solution section
    solution_title: str = Field(default="Here's how we fix it")
    solution_description: str = Field(description="Solution overview, 2-3 sentences")
    solution_features: list[SolutionFeature] = Field(
        min_length=3, max_length=3, description="3 key features with emoji"
    )

    # Benefits section
    benefits: list[Benefit] = Field(
        min_length=3, max_length=3, description="3 tangible, quantified benefits"
    )

    # Social proof section
    testimonials: list[Testimonial] = Field(
        min_length=2, max_length=3, description="2-3 testimonials with specific results"
    )

    # How it works section
    steps: list[Step] = Field(
        min_length=3, max_length=3, description="3 steps: sign up, configure, results"
    )

    # FAQ section
    faq: list[FAQ] = Field(min_length=4, max_length=6, description="4-6 common questions")

    # Final CTA
    urgency_text: str = Field(
        description="Urgency/scarcity text, e.g. 'First 100 users get lifetime access'"
    )

    # Meta tags
    page_title: str = Field(description="Page title for SEO, < 60 chars")
    meta_description: str = Field(description="Meta description, < 155 chars")

    # Branding
    brand_name: str = Field(description="Product/brand name")
    brand_color: str = Field(
        default="#E94560", description="Primary accent color (hex)"
    )


class LandingPageContentVariantB(BaseModel):
    """Alternate headline and CTA for A/B testing."""

    headline: str = Field(description="Alternate headline with different angle")
    subheadline: str = Field(description="Alternate subheadline")
    cta_text: str = Field(description="Alternate CTA text")
