from pydantic import BaseModel, Field


class LandingBrief(BaseModel):
    """Landing page brief extracted from PRD."""

    headline_suggestions: list[str] = Field(
        ..., min_length=2, max_length=3, description="2-3 headline options"
    )
    subheadline: str
    cta_text: str
    key_sections: list[str] = Field(description="Recommended landing page sections")
    messaging_angle: str = Field(description="Primary messaging angle (benefit vs pain)")


class AdsBrief(BaseModel):
    """Ads brief extracted from PRD."""

    target_demographics: str
    interests: list[str]
    suggested_daily_budget_eur: float = Field(default=7.0)
    test_duration_days: int = Field(default=5)
    creative_angles: list[str] = Field(
        description="3 different creative angles for ad variants"
    )
    tiktok_hashtags: list[str] = Field(default_factory=list)


class PRDContent(BaseModel):
    """Full PRD generated by Claude from an IdeaCard."""

    executive_summary: str = Field(description="1-paragraph summary")
    problem_statement: str = Field(description="Problem and pain points (2-3 paragraphs)")
    target_audience_analysis: str = Field(description="Who they are, demographics, behaviors")
    proposed_solution: str = Field(description="Solution description")
    key_features: list[str] = Field(description="3-5 core features")
    unique_value_proposition: str = Field(description="What makes this different")
    competitive_landscape: str = Field(description="Known competitors and positioning")
    success_metrics: list[str] = Field(description="KPIs to track")
    monetization_strategy: str = Field(description="How the product makes money")
    landing_brief: LandingBrief
    ads_brief: AdsBrief
